let object = [
    "UF Gator Baseball always looks for the best and that’s why we use G Tee made in Ocala, Florida USA since 2009. Whether you’re talking about quality, durability, functionality or customer service G Tee wins hands down every time. G Tee not only manufactures unrivaled batting tees, they also produce pitching aids that are second to none. We strive to train like professionals that’s why we use G Tee…what Pros use. Edmund BoydAssistant Director of Athletic Equipment and Gator Baseball’s Equipment Manager, University of Florida",
    "G Tees are the best in the business. It’s a family-owned business that cares more about people than profits. We will continue to use their products within our program for years to come. Patrick MurphyHead Softball Coach, University of Alabama",
    "G Tee is a quality product that I cannot do without in my bullpen. Using the G Tee pitching aids with my pitchers has helped with their visualization and precision. The functionality and performance of the G Tee products are top of the line. Joe and his staff are genuine, hardworking people who not only know how to make a legitimate product, but give you customer service that is outstanding! Jennifer RochaAssociate Head Coach, University of Oklahoma",
    "Since its inception, the G Tee has been the most practical, durable, and user friendly tee we have trained with. The variety of heights, and now the options with the base, allow for stability and superior variety with pitch locations. As always, their customer service remains A+. The G Tee has had a tremendous impact on the development of our players and the overall offensive production of our team. Link JarrettHead Baseball Coach, University of North Carolina at Greensboro",
    "I absolutely love the G Tee! Tee work is the best work for my swing and I find that the G Tee is the best tee I have ever used. It is extremely easy to set up, and easy for me to take on the road. I am constantly traveling the world and the G Tee is easy to break down and put in my bat bag. I love how I can work on low pitches as well as high pitches to help perfect my swing! G Tee is an investment that you won't regret. Kelsey StewartTeam USA, Former University of Florida Gators Player",
    "We have been using the G Tee Pitching sticks at the University of Oregon for over a year and they have proved to be an invaluable tool in helping our pitchers improve their location on all pitches. They are extremely durable, portable and easy to set up. The G Tee Pitching Sticks are a “must have” in any coaches program that is serious about improving their pitcher’s location. Mike WhiteHead Softball Coach, University of Oregon",
    "I love quality products and the G Tee guarantees exactly that! Speaking as a former collegiate and professional player, we want products that can help set us up for success. The G Tee is dependable and reliable, with the best engineering to ensure quality for years to come. Match this product with the guys behind it and I can assure you we are lifers with the G Tee. Our kids we train through lessons, camps and clinics will have this product in hand as we train for success. Stephanie BestProSwings Founder",
    "I have been coaching baseball since 1990 and directing camps and participating in camps since 1998.  I have used many different types of batting tees over the those years and some are reliable for a period of time but there are none as durable and reliable as G Tee Batting Tees.  I believe the integrity and durability of their product is a direct reflection of the integrity of the ownership and management of their company.  They are always professional and responsive with getting you your orders in a timely manner.  The warranty they provide also is another aspect of the integrity they have in standing behind the quality and durability of their product. Barry BatsonAssistant Baseball Coach, State College of Florida - Manatee",
    "The G Tee is the best tee that is available period. I've used the same tees and attachments going on 5 years now!  I personally love the low ball attachments because you can practice hitting pitches that are actually being thrown in the games. Learning to use your legs and attack low pitches improved my hitting drastically. These attachments are not offered on any other tee. If you are looking for a tee that is approved and used by professionals look no further, the G Tee is for you! Allan DykstraDykstra Baseball, Former MLB Player",
    "In the eight years as the head coach at Biola University, we have gone through many hitting tees. Typically at the end of each season, we would dispose of all the hitting tees because they were literally in pieces by the end of season. Each year we had to start all over with a new set of tees! It wasn't until we ordered our first G Tee that we were able to begin a collection of tee sets that have lasted over three years and counting! We absolutely love G Tee and won't be using any other product! Lorie ColemanHead Softball Coach, Biola University",
    "I've been using G Tees ever since I was little. They last forever, and I can easily take them with me wherever I go. They're the best tees in the game. Sami FaganProfessional Softball Player, Akron Racers",
    "As the hitting coach here at Ole Miss softball we have been blessed to use G Tees on an everyday basis. These tees were a big part of us breaking every offensive record held here at Ole Miss and us hitting over .300 as a team in 2015. I would highly recommend these tees as they are a great tool to help high level softball/baseball players. Ruben FelixHitting Coach, Ole Miss",
    "Never before in my 20 years involved in amateur and professional baseball, have I dealt with such a great tee. The G Tee is by far the best one: durable, easy to adjust, and the best thing about the G Tee is the quick snap on adjustment for low ball. The G Tee does it all, and it will give you success in hitting if properly used. Kundy GutierrezFounder/Owner, The Baseball Legends",
    "A Tee is not just a Tee. Top 3 reasons why the G Tee is an effective hitting tool. 1. Portability. 2. Low Ball Training. 3. Durability. The G should stand for GANGSTA. Rob CrewsFounder, Instructor & Author, Complete Game LLC",
    "We exclusively use the G Tee at RHINO Baseball Wisconsin and Premier Athletics for all our TEAM practices and private lessons. We like to integrate multiple variations of tee work, and the G Tee’s versatility allows for that. The durability and consistency are second to none. Great product, great people, we are excited to be a part of the G Tee family! Joe ShovaldHitting Coordinator, RHINO Baseball Wisconsin",
    "I have been coaching for over 20 years, and the G Tee is the first batting tee that has withstood the everyday rigors of practice. Many tees I have used in the past have broken during the season, and the G Tee is the first batting tee that didn’t break throughout its use during a season! I also love the short tee that can be used for lower pitches. I would recommend the G Tee to anyone who wants an excellent quality batting tee that will last for years. I've coached for over 20 years, the G Tee is the first tee that has withstood daily rigors of practice. Courtney MillerHead Softball Coach, Seminole State College of Florida",
    "At Stetson University, we love utilizing the G Tees. The G Tee is a durably reliable and efficient practice tool. Frank GriffinHead Softball Coach, Stetson University",
    "The G Tee has truly changed my opinion of those annoying hitting tees that fall over constantly on a mishit. In my 23 years of playing softball, this is the most logical hitting tee that I have used. Not only is it durable, but it is easy to assemble when using the different tee attachments, extremely portable when traveling from my practices and personal hitting lessons, and stands upright with the help of the 10 lb. weight. So happy that I was introduced to the G Tee; will never use another hitting tee from this point forward. Amber PattonChicago Bandits",
    "I have been using the G Tee for a few years now. I can honestly tell you that the G Tee has allowed our players to get quality swings on this tee and very durable as well. Hitting off a tee is a very important aspect of hitting and the center building block for being a great hitter. I have been very pleased with the G Tee and recommend it to everyone and every team. Troy CanabaHead Softball Coach, Sul Ross State University",
    "The G Tee is a major part of our total hitting program and helps set the solid foundation that my team requires to compete in one of the toughest JUCO softball regions in the nation. The G Tee was one of the first team equipment purchases I made when arriving at Vernon College and it’s one that I don’t believe you can go wrong with. Melvin JenkinsHead Softball Coach, Vernon College, Vernon, TX",
    "I absolutely love my G Tee Batting Tee!! It’s so nice to travel with as it’s able to break down quickly and become very compact. With my lifestyle, I’m always on the go and need something that I can tote around easily with. I also appreciate how durable it is! Megan WillisNational Pro Fastpitch for USSSA Florida Pride",
    "Our coaching staff believes the G Tee is a must in any hitting coach's arsenal. The G Tee gives you the ability to work various zones of the plate and various heights of pitches. The feature to raise and lower the G Tee assists all coaches in creating effective as well as unique training sessions. The design is very durable and travels easily as well. The days of setting tees on a bucket or milk crates are over. The G Tee will be a big help for the softball program here for many years. Angel SantiagoHead Softball Coach, Nicholls State University",
    "We use the G Tee here at our softball program at the University of Arkansas for one reason, it is hands down the best tee on the market. The durability of the G Tee will allow them to be used year after year. Where other tees have to be replaced annually, The G Tee will be with you season after season. It is a great American made product that is made by a family valued company. I highly recommend anyone in baseball or softball at any level to give The G Tee a shot. Mike LarabeeHead Softball Coach, University of Arkansas",
    "Our players absolutely love the G Tee. We’ve taken thousands of swings off of it since we got it, and it still looks like it just came out of the box. It blows away any other tee we have ever tried. Troy NakamuraAssistant Baseball Coach, Recruiting Coordinator, University of San Francisco",
    "I would like to thank you and your company for coming up with such a remarkable hitting tee. Not only do I coach at the junior college level in southern California, I also teach private lessons to big leaguers and to little leaguers. The flexibility in your tee for various heights from as low as 16 inches to 53 inches is amazing. I have had at least 15,000 to 20,000 swings on my personal G Tee and it still looks brand new. I love the no tipping over and the durability. I love this tee so much that I have shared this info with some of my big league coach friends and players. If you love to hit, and hit various locations high and low, I would highly recommend the G Tee. Roger FrashHead Assistant Baseball Coach, Oxnard College",
    "I believe that one of the key elements in developing a hitter is through coaching and training with a batting tee. The G Tee is by far, the best batting tee I have seen in all of my years of coaching. Mik AokiHead Baseball Coach, University of Notre Dame",
    "One of the staples of our practices is working everyday on the batting tee. The new G Tee Batting Tee is a great new product for your team to use in developing a consistent swing. It is lightweight, durable, and easy to adjust for any player. If you want your team’s average to improve-the G Tee is a great tool to use. For camps, clinics, and everyday use it is an outstanding product. I highly recommend it for all age and skill levels. Jay MillerHead Softball Coach, Mississippi State University, USA National Team",
    "The G Tee Batting Tee is by far the most portable, durable, and effective teaching tool that I have seen in a long time. Not only does this tee provide you with durability, it also adjusts easily to give you the opportunity to work both High and Low pitches in the zone. The cone shaped top provides a great hitting surface that allows you to hit through the ball without breaking or splitting. I have used many tees in my 30+ years of coaching and would highly recommend the G Tee Batting Tee. It will be the last tee you will ever purchase! Mike CandreaHead Softball Coach, The University of Arizona, NCAA National Champions 1991, 93, 94, 96, 97, 2001, 06, 07",
    "The G Tee is the best stationary batting T you can use, period! It’s strong enough to handle whatever punishment you give it and light enough so you can easily carry it wherever you need to go. It’s up and down capabilities are fantastic as they help your hitters handle the riseball at the top of the zone and the dropball at the bottom – and it never slips down under the weight of the ball. I love it! Cindy BristowOwner, Softball Excellence, NFCA Hall of Famer",
    "In my 22 years of coaching college baseball I have gone through many batting tees trying to find the perfect tee as far as durability and versatility. From the hard plastic tees that damaged bats to the poorly made flimsy tees that only lasted a month I have spent countless dollars trying different tees. Finally, The G Tee combines everything I need into a durable, versatile, lightweight and transportable tee that is affordable and lasts a long time. From Little League to the professional ranks, The G Tee is the perfect tee!! Marty SmithHead Baseball Coach, College of Central Florida",
    "The G Tee is by far the most durable and functional tee ever made. We have literally thousands of swings on our G Tee’s without any breakdowns. The high to low range of the tee and how fast and easy the adjustments are made let us practice hitting in all parts of the strike zone, as well as isolating specific hitting needs for each individual. The fact that they are so portable is an added bonus. Kevin FaganHead Softball Coach, College of Central Florida",
    "The best batting tee that I have seen or used in 35 years of coaching high school baseball is the G Tee. The high quality of the tee makes it durable and its assembly makes it easy to use. It can be taken apart and placed in a carry bag in minutes. The G Tee is an instrumental part of our everyday hitting program. All levels of our players are using the G Tee to improve their hitting skills. Height adjustments are made quick and easy, almost unbelievable! Wayne YanceyHead Baseball Coach, Forest High School",
    "I’m Crystl Bustos former Olympian and current clinician and owner of Got Bustos? Sports Training, LLC. We use the G Tee Batting Tee for camps, clinics and lessons. I really like the professional look of the G Tee and how easy it is to travel with. With the G Tee’s adjustable heights the players can train to hit the high pitch as well as my favorite, the low pitches with the Low Ball Attachment which is also available. I enjoy working with the great group of people at G Tee Batting Tees who are always putting the player’s needs and training into their product development. Trust me when I say this is a great, durable piece of equipment where you can get “the most bang for your buck”. Crystl Bustos",
    "I have been coaching at the University of Tennessee since 2002. We believe in using the best equipment on the market to train our players. Not only is the G Tee’s quality unparalleled, their customer service always surpasses my expectations. Ralph WeeklyCo-Head Coach, University of Tennessee",
    "The G Tee is a great hitting device for hitters of all ages. I love the high-low capability that it provides for hitters of all sizes. The G Tee is simply a very portable and durable tee that truly makes a difference in the way you can prepare to be a better hitter. Tim WaltonHead Softball Coach, University of Florida",
    "The G Tee is the best tee on the market hands down. If you’re serious about becoming a better hitter you need to buy the G Tee. It’s durability and versatility is what sets it apart. So if you want to hit like a pro you better use what the pros use. The G Tee!! Jason RomanoBusiness Development Director, Former MLB Player",
    "I’ve been in Professional baseball since 2004. I love the G Tee, I use mine every day and it’s greatly improved my game. Being a power hitter I’ve always had to deal with the slight upper cut in my swing and I really like the high tee feature of the G Tee. It’s helped me learn to get on top of the baseball and drive it with some back spin the right way. So I highly recommend the G Tee for anyone who is looking to improve their game. Russ CanzlerTampa Bay Rays",
    "I’ve been playing Professional baseball since 2006. I’ve used every other tee out there and by far the G Tee is the best there is. It goes to every height I want, it goes up to my shoulders to do my high tee work, it goes down right below my knees to get my low ball work in, so it’s the only tee I take to the field. It fits easily in my bag, it’s very portable and it’s the only tee I’ll ever use. Nathan SamsonIowa Cubs"
];

object.forEach(function(elements){
    console.log(elements)
})



